version: '3.4'

services:
  aspnetapp.frontend:
    image: ${DOCKER_REGISTRY-}aspnetapp.frontend
    build:
      context: .
      dockerfile: src/aspnetapp.frontend/Dockerfile
      args:
#       sdkImage: kdcllc/dotnet
#       sdkTag: 2.2-sdk
#       runtimeImage: microsoft/dotnet
#       runtimeTag: 2.2-aspnetcore-runtime
#       coreversion: netcore22
        sdkImage: kdcllc/dotnet
        sdkTag: 3.0-sdk
        runtimeImage: mcr.microsoft.com/dotnet/core/aspnet
        runtimeTag: 3.0.0-preview6-buster-slim
        coreversion: netcore30
        # verbose: "true"
  aspnetapp.sqldb:
   image: microsoft/mssql-server-linux