
ARG sdkImage
ARG sdkTag
ARG runtimeImage
ARG runtimeTag
# ARG PROJECT_PATH=./src/WebApp30/WebApp30.csproj

# Build image
FROM ${sdkImage}:${sdkTag} as builder
RUN dotnet publish "./src/WebApp30/WebApp30.csproj" -c Release -o /app

# App image
FROM ${runtimeImage}:${runtimeTag} AS final
WORKDIR /app
EXPOSE 80
EXPOSE 443

COPY --from=builder /app .
ENTRYPOINT ["dotnet", "WebApp30.dll"]
