version: '3.4'

services:
  dotnet.builder:
    image: dotnet:2.1-builder
    build:
      context: .
      dockerfile: Dockerfile
      args:
       image: microsoft/dotnet
       sdkTag: 2.1-sdk
       runtimeTag: 2.1-aspnetcore-runtime
       coreversion: netcore21
    volumes:
      - ${BUILD_ARTIFACTSTAGINGDIRECTORY:-./TestResults/}:/var/temp