version: '3.4'

services:
  aspnetapp.frontend:
    image: aspnetapp.frontend
    build:
      context: .
      dockerfile: src/aspnetapp.frontend/Dockerfile
      args:
       DOTNET_VERSION: netcore31
       RUNTESTS: "false"
       VERBOSE: "false"
       #NUGET_RESTORE: "-f"

  aspnetapp.sqldb:
   image: microsoft/mssql-server-linux