version: '3.4'
# docker push kdcllc/dotnet:2.1-sdk

services:
  dotnet.builder.21:
    image: kdcllc/dotnet:2.1-sdk
    build:
      context: .
      dockerfile: Dockerfile
      args:
       image: mcr.microsoft.com/dotnet/core/sdk
       sdkTag: 2.1
       NODE_VERSION: 10.16.0
    volumes:
      - ${BUILD_ARTIFACTSTAGINGDIRECTORY:-./TestResults/}:/var/temp
  
  dotnet.builder.22:
    image: kdcllc/dotnet:2.2-sdk
    build:
      context: .
      dockerfile: Dockerfile
      args:
       image: mcr.microsoft.com/dotnet/core/sdk
       sdkTag: 2.2
       NODE_VERSION: 10.16.0

    volumes:
      - ${BUILD_ARTIFACTSTAGINGDIRECTORY:-./TestResults/}:/var/temp
  
  dotnet.builder.30:
    image: kdcllc/dotnet:3.0-sdk
    build:
      context: .
      dockerfile: Dockerfile
      args:
       image: mcr.microsoft.com/dotnet/core/sdk
       sdkTag: 3.0.100-preview6
       NODE_VERSION: 10.16.0
    volumes:
      - ${BUILD_ARTIFACTSTAGINGDIRECTORY:-./TestResults/}:/var/temp