version: '3.4'
# docker push kdcllc/dotnet:2.1-sdk

services:
  dotnet.builder.21:
    image: kdcllc/dotnet:2.1-sdk
    build:
      context: .
      dockerfile: Dockerfile
      args:
       image: microsoft/dotnet
       sdkTag: 2.1-sdk
       coreversion: netcore21
       nodeVersion: 10.14.1
    volumes:
      - ${BUILD_ARTIFACTSTAGINGDIRECTORY:-./TestResults/}:/var/temp
  
  dotnet.builder.22:
    image: kdcllc/dotnet:2.2-sdk
    build:
      context: .
      dockerfile: Dockerfile
      args:
       image: microsoft/dotnet
       sdkTag: 2.2-sdk
       coreversion: netcore22
       nodeVersion: 10.14.1

    volumes:
      - ${BUILD_ARTIFACTSTAGINGDIRECTORY:-./TestResults/}:/var/temp
  
  dotnet.builder.30:
    image: kdcllc/dotnet:3.0-sdk
    build:
      context: .
      dockerfile: Dockerfile
      args:
       image: microsoft/dotnet
       sdkTag: 3.0-sdk
       coreversion: netcore30
       nodeVersion: 10.14.1
    volumes:
      - ${BUILD_ARTIFACTSTAGINGDIRECTORY:-./TestResults/}:/var/temp