version: '3.4'

# Azure DevOps enabled (3.0 release)
# base development sdk with nodejs installed:
# docker push kdcllc/dotnet:3.0-sdk-base-buster
#
# vscode remote container development environment:
# docker push kdcllc/dotnet:3.0-sdk-vscode-buster
#
# docker sdk container for development
# docker push kdcllc/dotnet:3.0-sdk-buster

services:
  # base image
  dotnet.builder.base:
    image: kdcllc/dotnet:3.0-sdk-base-alpine
    build:
      context: .
      dockerfile: Dockerfile.alpine.base30
      args:
       image: mcr.microsoft.com/dotnet/core/sdk
       sdkTag: 3.0-alpine
       NODE_VERSION: 12.10.0
  
  # vscode image with remote debugging
  # dotnet.builder.vscode:
  #   image: kdcllc/dotnet:3.0-sdk-vscode-buster
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.vscode
  #     args:
  #      image: kdcllc/dotnet
  #      sdkTag: 3.0-sdk-base-buster
  
  # docker development image
  dotnet.builder.dev:
    image: kdcllc/dotnet:3.0-sdk-alpine
    build:
      context: .
      dockerfile: Dockerfile.full
      args:
       image: kdcllc/dotnet
       sdkTag: 3.0-sdk-base-alpine
  
  dotnet.builder.dev.light:
    image: kdcllc/dotnet:3.0-sdk-light-alpine
    build:
      context: .
      dockerfile: Dockerfile.light
      args:
       image: kdcllc/dotnet
       sdkTag: 3.0-sdk-base-alpine
