version: '3.4'

# Azure DevOps enabled
# base development sdk with nodejs installed:
# docker push kdcllc/dotnet:2.1-sdk-base
#
# vscode remote container development environment:
# docker push kdcllc/dotnet:2.1-sdk-vscode
#
# docker sdk container for development
# docker push kdcllc/dotnet:2.1-sdk

services:
  # base image
  dotnet.builder.base:
    image: kdcllc/dotnet:2.1-sdk-base
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
       image: mcr.microsoft.com/dotnet/core/sdk
       sdkTag: 2.1
       NODE_VERSION: 10.16.0
  
  # vscode image with remote debugging
  dotnet.builder.vscode:
    image: kdcllc/dotnet:2.1-sdk-vscode
    build:
      context: .
      dockerfile: Dockerfile.vscode
      args:
       image: kdcllc/dotnet
       sdkTag: 2.1-sdk-base
  
  # docker development image
  dotnet.builder.dev:
    image: kdcllc/dotnet:2.1-sdk
    build:
      context: .
      dockerfile: Dockerfile.full
      args:
       image: kdcllc/dotnet
       sdkTag: 2.1-sdk-base
    volumes:
      - ${BUILD_ARTIFACTSTAGINGDIRECTORY:-./TestResults/}:/var/temp