version: '3.4'

# base development sdk with nodejs installed:
# docker push kdcllc/dotnet:3.0-sdk-base-bionic
#
# vscode remote container development environment:
# docker push kdcllc/dotnet:3.0-sdk-vscode-bionic
#
# docker sdk container for development
# docker push kdcllc/dotnet:3.0-sdk-bionic

services:
  # base image
  dotnet.builder.base:
    image: kdcllc/dotnet:3.0-sdk-base-bionic
    build:
      context: .
      dockerfile: Dockerfile.base30
      args:
       image: mcr.microsoft.com/dotnet/core/sdk
       sdkTag: 3.0.100-preview8-bionic
       NODE_VERSION: 10.16.0
  
  # vscode image with remote debugging
  dotnet.builder.vscode:
    image: kdcllc/dotnet:3.0-sdk-vscode-bionic
    build:
      context: .
      dockerfile: Dockerfile.vscode.full
      args:
       image: kdcllc/dotnet
       sdkTag: 3.0-sdk-base-bionic
  
  # docker development image
  dotnet.builder.dev:
    image: kdcllc/dotnet:3.0-sdk-bionic
    build:
      context: .
      dockerfile: Dockerfile.full
      args:
       image: kdcllc/dotnet
       sdkTag: 3.0-sdk-base-bionic
    volumes:
      - ${BUILD_ARTIFACTSTAGINGDIRECTORY:-./TestResults/}:/var/temp