version: '3.4'

# docker-compose -f "docker-compose.dev.yml" up -d --force-recreate --build
services:
  app:
    image: webapp30
    build:
      context: .
      dockerfile: src/WebApp30/Dockerfile.build
      args:
        sdkImage: kdcllc/dotnet-sdk
        sdkTag: 3.1
        runtimeImage: mcr.microsoft.com/dotnet/core/aspnet
        runtimeTag: 3.1
        RUNTESTS: "true"
        VERBOSE: "false"
        PROJECT_PATH: /src/WebApp30/WebApp30.csproj
        SOLUTION_BASE: "false"
        DOTNET_VERSION: ""
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=7001

    volumes:
        # dotnet dev-certs https -ep C:\Users\Root\AppData\Roaming\ASP.NET\Https\WebApp30.pfx -p fea04367-1bda-4cde-8989-2d1e06dfa48d
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${BUILD_ARTIFACTSTAGINGDIRECTORY:-./TestResults/}:/var/temp

    ports:
      - "7000:80"
      - "7001:443"
